# coding=utf-8
# Using UTF-8 for better compatibility across modern systems.

# --- LIBRARIES ---
import streamlit as st
import requests
import json
import uuid

# --- STREAMLIT PAGE CONFIGURATION ---
# page_title: Sets the browser tab title.
# layout="wide": Uses the full width of the screen.
st.set_page_config(page_title="StressSense AI Analyzer", layout="wide")

# --- FUNCTION DEFINITION ---

def query_chatbot(session_id, user_message):
    """
    Sends a request to the n8n webhook to get the chatbot's response.

    Args:
        session_id (str): Unique ID to maintain conversation context in n8n.
        user_message (str): The text input from the user.

    Returns:
        str: The response generated by the AI agent.
    """
    # Replace this with your actual n8n production or test URL
    url = "https://akashaigents.app.n8n.cloud/webhook/streamlitchat"    
    
    # Create the JSON payload for the n8n request
    payload_dict = {
        "session": session_id,
        "message": user_message
    }
    
    payload = json.dumps(payload_dict)
    
    # Headers to inform the server we are sending JSON data
    headers = {
        'Content-Type': 'application/json'
    }
    
    # Send the POST request to n8n
    response = requests.post(url, headers=headers, data=payload)
        
    # Check for HTTP errors
    response.raise_for_status()
        
    # Parse the JSON response
    response_json = response.json()
        
    # Returns the value of the "output" key from the n8n workflow
    return response_json["output"]
        
    

# --- UI HEADER ---
st.title(" StressSense: Digital Well-being Analyzer")
st.markdown("Analyze your digital patterns and manage stress effectively.")

# --- SESSION STATE MANAGEMENT ---
# Ensures the chat history persists during user interactions (reruns).

if "messages" not in st.session_state:
    st.session_state.messages = []

# Generate a unique session ID if it doesn't exist.
if "session_id" not in st.session_state:
    st.session_state.session_id = uuid.uuid4().hex

# --- CHAT HISTORY VISUALIZATION ---
for message in st.session_state.messages:
    # Set avatars: user-svgrepo-com.png for the user, robot-one-svgrepo-com.png for the AI
    avatar_img = "robot-one-svgrepo-com.png" if message["role"] == "assistant" else "user-svgrepo-com.png"
    with st.chat_message(message["role"], avatar=avatar_img):
        st.markdown(message["content"])

# --- USER INPUT ---
if prompt := st.chat_input("How are you feeling today?"):

    # Store and display the user message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user", avatar="user-svgrepo-com.png"):
        st.markdown(prompt)

    # Call the n8n webhook
    with st.spinner("Analyzing stress patterns..."):
        ai_response = query_chatbot(
            st.session_state.session_id,
            user_message=prompt
        )

    # Display the AI response
    with st.chat_message("assistant", avatar="robot-one-svgrepo-com.png"):
        st.write(ai_response)
    
    # Save to history
    st.session_state.messages.append({"role": "assistant", "content": ai_response})
